# Generated by Django 4.2.2 on 2024-04-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("users", "0004_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="course_paid",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите оплаченный курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_course",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="lesson_paid",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите оплаченный урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_lesson",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
