# Generated by Django 4.2.2 on 2024-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payments_link_pay_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "наличные"), ("transfer", "перевод на счет")],
                default="daily",
                help_text="Выберите способ оплаты",
                max_length=255,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
